### ISSUE TITLE
Preloader Creator for Bludit v 4.0

### ISSUE THREAD

**Issue by prokoleg** [multicolor-rgb/preloader-creator-for-bluditcms#1]
Hello! I have not been able to properly adapt your plugin for Bludit 4.0. For some reason, the **siteHead** function is not loaded from your plugin into the system itself. I wrote the styles with my hands directly into the template. How can this be fixed?

Will there be a full-fledged plugin for Bludit 4.0 and how soon to wait for it?

Special thanks for the plugin.

**Comment by multicolor-rgb** [comment]
Hey, 
Thanks for use it:) I will check this and before end this week i upload version for bludit 4.0 :)

**Comment by prokoleg** [comment]
Thanks, and then I'll see what I did wrong.

**Comment by multicolor-rgb** [comment]
please tell me did you use own template or something ready to use from bludit themes?

**Comment by prokoleg** [comment]
I used a template from the cms author. Kolika template

**Comment by multicolor-rgb** [comment]
ohh, on default included on v4 default template preolader works ok, something on theme problem.

**Comment by multicolor-rgb** [comment]
i check this- please wait

**Comment by multicolor-rgb** [comment]
if you use this theme https://themes.bludit.com/theme/kolika this is not fully compatible with 4.0 - please check preolader creator works on another theme and tell me if works or not.

**Comment by prokoleg** [comment]
Yes, everything works fine on default themes. I will rewrite the theme for your plugin to make it easier for other users.
Thanks for the feedback
